export type LinkItem = { label: string; href: string; external?: boolean };
export type Experience = { id: string; title: string; eyebrow: string; href: string; image: string; alt: string; summary: string; setting: string; experience: string; when: string; where?: string; admission: string; highlights: string[]; ctas: LinkItem[]; schemaName: string };

export const site = { name: "Fiddler on the Rock", url: "https://www.fiddlerontherock.com", owner: "Tyler Carson", location: "Sedona, Arizona", description: "Live violin concerts and private Living Music experiences in Sedona's Red Rock landscape. As seen on CBS Mornings.", indiegogo: "https://www.indiegogo.com/en/projects/softsign_c14951cf-838e-4a13-a24a-1b524b5cc04a/fiddler-on-the-rock-reaching-for-the-stars" };
export const navLinks: LinkItem[] = [{ label: "Home", href: "/" }, { label: "Live Concerts", href: "/live-concerts" }, { label: "Private Events", href: "/private-events" }, { label: "Media & Merch", href: "/media-merch" }];
export const mediaLinks: LinkItem[] = [
  { label: "EPK", href: "/epk" },{ label: "CBS", href: "/cbs" }, { label: "Documentary", href: "/documentary" }, { label: "Videos", href: "/videos" }, { label: "Music", href: "/music" }];
export const socialLinks = [{ label: "Instagram", href: "https://www.instagram.com/fiddlerontherock/", icon: "instagram" }, { label: "Facebook", href: "https://www.facebook.com/fiddlerontherock/", icon: "facebook" }, { label: "YouTube", href: "https://www.youtube.com/@fiddlerontherock", icon: "youtube" }, { label: "Spotify", href: "https://open.spotify.com/search/tyler%20carson", icon: "spotify" }, { label: "Apple Music", href: "https://music.apple.com/us/search?term=Tyler%20Carson", icon: "apple" }];
export const home = { headline: "Elevate Your Sedona Experience with the Soundtrack of the Red Rocks.", seoHeadline: "Fiddler on the Rock: Sedona's Premier Live Music & Sunset Experience", subheadline: "Join virtuoso Tyler Carson for an immersive, CBS-featured sunset concert that connects you to the heartbeat of Sedona.", primaryCta: { label: "Get Concert Tickets", href: "/live-concerts" }, secondaryCta: { label: "Book a Private Event", href: "/private-events" } };

export const experiences: Experience[] = [
  { id: "one-man-symphony", title: "One Man Symphony", eyebrow: "Thursdays in the Red Rocks", href: "/one-man-symphony", image: "/images/legends-stage-hero.jpg", alt: "Tyler Carson performing on stage", summary: "Tyler's signature one-man-orchestra: loop pedals, rare horn violin, and a private canyon stage as Sedona does what Sedona does to the light.", setting: "A private Red Rock stage near the Sedona Heritage Museum, with the canyon light shifting toward gold around the audience.", experience: "Loop pedals and rare horn violin weave Led Zeppelin, Disney, Taylor Swift, originals, and personal stories into a concert that feels like an entire orchestra meeting the landscape.", when: "Thursdays, 5:45 PM. Doors open at 5:00 PM.", where: "Sedona Heritage Museum / Apple Barn area", admission: "$55 General | $85 VIP", highlights: ["As seen on CBS Mornings", "Free museum entry with every ticket", "Small audience by design"], ctas: [{ label: "General Admission", href: "/booking?show=one-man-symphony&tier=general" }, { label: "VIP Admission", href: "/booking?show=one-man-symphony&tier=vip" }], schemaName: "One Man Symphony - Fiddler on the Rock" },
  { id: "sedona-serenades", title: "Sedona Serenades", eyebrow: "Exclusive private violin experience", href: "/private-events", image: "/images/red-rock-concert.jpg", alt: "Private Sedona Serenades violin concert at sunset", summary: "A private outdoor concert built entirely for your group. You hike in, Tyler plays, the canyon holds you.", setting: "Choose The Secret Spot for a short walk into a natural canyon formation, or The Open-Air Spot for flat, accessible Red Rock views.", experience: "A full private Living Music concert as the canyon light shifts around you. The sound of the violin meets the silence of the Red Rocks, with guided dialogue between pieces.", when: "Scheduled around your visit from direct-bookable availability slots.", where: "The Secret Spot or The Open-Air Spot, Sedona", admission: "Romantic Escape starts at $399 for two", highlights: ["Private by definition", "Ideal for proposals and anniversaries", "Add custom songs or chocolates"], ctas: [{ label: "Book Serenades", href: "/booking?show=sedona-serenades" }, { label: "Request Custom Event", href: "/contact?booking=request" }], schemaName: "Sedona Serenades - Private Violin Experience" },
  { id: "legends-of-the-fiddle", title: "Legends of the Fiddle", eyebrow: "Saturdays at Sedona Dances HQ", href: "/legends-of-the-fiddle", image: "/images/one-man-symphony-green-flannel.jpg", alt: "Tyler Carson smiling in a green flannel shirt with violin at the Sedona Heritage Museum", summary: "Tyler's most theatrical show: cinematic, mythic, and technically extraordinary, with one violin filling the room.", setting: "Sedona Dances Headquarters in West Sedona, built for an immersive indoor concert experience.", experience: "A journey through the legends that shaped the violin: Celtic fire, classical triumph, the devil going down to Georgia, and Tyler's own story of recovery and resilience.", when: "Saturdays, 6:45 PM. Doors open at 6:30 PM.", where: "Sedona Dances Headquarters, West Sedona", admission: "$55 General | $85 VIP", highlights: ["Debuted to a sold-out house at SIFF", "Patrick Schweiss called Tyler extraordinary", "As seen on CBS Mornings"], ctas: [{ label: "General Admission", href: "/booking?show=legends-of-the-fiddle&tier=general" }, { label: "VIP Admission", href: "/booking?show=legends-of-the-fiddle&tier=vip" }], schemaName: "Legends of the Fiddle - Fiddler on the Rock" }
];
export const decisionTree = [{ prompt: "First time in Sedona?", recommendation: "Start with One Man Symphony.", body: "A private Red Rock stage at sunset and Tyler's full one-man-orchestra experience. This is the classic Sedona evening." }, { prompt: "Planning something unforgettable for someone you love?", recommendation: "Choose Sedona Serenades.", body: "A private concert in the Red Rocks, built for proposals, anniversaries, and the kind of night that becomes a family story." }, { prompt: "Ready for a full concert experience?", recommendation: "Book Legends of the Fiddle.", body: "Cinematic, mythic, and technically extraordinary. Saturday evenings at Sedona Dances HQ." }, { prompt: "Can't decide?", recommendation: "Many guests book all three.", body: "Each one is a different doorway into Tyler's music. Together, they are the complete Sedona sound." }];
export const cbs = { youtubeId: "Uh0ckhgVxJM", title: "Tyler Carson on CBS Mornings", headline: "As Seen on CBS Mornings", subheadline: "CBS Mornings traveled to Sedona to cover Tyler Carson's story: a violinist who lost his voice and found something more powerful.", quote: "That was so fun!! You are such a great player.", attribution: "Lindsey Stirling, on CBS Mornings after performing with Tyler Carson", body: "The segment was not only about a concert. It was about what happens when a musician loses the ability to speak and discovers that the violin can do what the voice no longer can. CBS followed Tyler into the Red Rocks, into the canyon where he performs, and into the story of spasmodic dysphonia, recovery, and music as survival." };
export const documentary = { youtubeId: "SgLyS1mI-VA", headline: "Living Music", subheadline: "The award-winning short documentary about Tyler Carson, Fiddler on the Rock, and the moment music became his voice.", body: "Living Music is the short documentary from BluPrint Films LA following Tyler Carson, the Sedona violinist behind Fiddler on the Rock. After spasmodic dysphonia changed his ability to speak, Tyler found that the violin could carry what words could not. The film follows that story into the Red Rocks, where performance becomes presence and music becomes survival, healing, and invitation. Living Music has screened as an award-winning documentary short and official selection at festivals including Illuminate, Prescott, Madrid, St. Louis, Awareness, and BendFilm.", quote: "EXTRAORDINARY doesn't even begin to describe this multi-talented performer, composer, and musical genius.", attribution: "Patrick Schweiss, Executive Director, Sedona International Film Festival" };
export const epk = {
  headline: "Tyler Carson",
  subheadline: "Fiddler on the Rock",
  kicker: "Thirty-five years. One instrument. No ceiling.",
  location: "Sedona, Arizona",
  show: "One Man Symphony",
  date: "Electronic Press Kit - May 2026",
  image: "/images/epk/tyler-red-rock.jpg",
  jumpImage: "/images/epk/tyler-jump-hero.jpg",
  wordmark: "/images/epk/fotr-wordmark-light.png",
  bio: [
    "Tyler Carson plays the violin with the kind of conviction that makes audiences forget what room they're in. His style defies easy categorization: classical precision, Celtic fire, improvisation, and the genre he calls Living Music.",
    "Tyler grew up in Victoria, British Columbia, with a violin in hand before most children hold a pencil. He was a classical soloist with the Victoria Symphony at thirteen and went on to tour across Canada, Japan, Thailand, Germany, and the Cayman Islands.",
    "Everything changed when Tyler lost his voice. Spasmodic dysphonia stripped away his ability to sing and speak normally. What followed was not a setback, but a becoming. The violin became the voice that could still carry the story.",
    "Today Tyler performs every Thursday in the Red Rock landscape of Sedona, where the canyon becomes the concert hall and the violin fills the kind of silence most people have stopped knowing how to find."
  ],
  downloads: [
    { label: "Press Photos", href: "/images/epk/tyler-red-rock.jpg" },
    { label: "Jump Hero", href: "/images/epk/tyler-jump-hero.jpg" },
    { label: "Logo", href: "/images/epk/fotr-logo-white.png" },
    { label: "Wordmark", href: "/images/epk/fotr-wordmark-light.png" }
  ]
};

export const epkPressItems = [
  { outlet: "CBS Mornings", logo: "/images/epk/cbs-mornings.jpg", title: "The story of violinist Tyler Carson, the Fiddler on the Rock", href: "https://www.cbsnews.com/video/the-story-of-violinist-tyler-carson-the-fiddler-on-the-rock/", summary: "Natalie Morales spoke with Tyler Carson in Sedona about beauty, hope, healing, and the unexpected turn that drew him to the Red Rocks.", featured: true },
  { outlet: "Sedona Red Rock News", logo: null, title: "Fiddling with the Red Rocks", href: "https://www.redrocknews.com/2023/12/28/fiddling-with-the-red-rocks/", summary: "A profile tracing Tyler's path from classical training in Canada to touring with major Celtic acts and becoming Sedona's Fiddler on the Rock." },
  { outlet: "Insight Timer", logo: null, title: "Featured Artist Profile", href: "https://insighttimer.com/fiddlerontherock", summary: "Featured on the meditation platform for Tyler's lifelong connection to violin and Living Music." },
  { outlet: "Discover the Phoenix Region", logo: "/images/epk/dtpr-cover.png", title: "Fiddler on the Rock - Up and Coming from the Red Rocks of Sedona", href: "https://discovertheregion.com/fiddler-on-the-rock-up-and-coming-from-the-redrocks-of-sedona/", summary: "Cover story on Tyler's formative years, early performances, classical training, and fiddle roots." },
  { outlet: "Visit Sedona", logo: null, title: "Sedona's Unique Musical Experience: Fiddler on the Rock", href: "https://visitsedona.com/blog/discover-sedonas-unique-musical-experience-fiddler-on-the-rock/", summary: "Official tourism feature about the show, Tyler Carson, and the Sedona concert experience." }
];

export const pressItems = [
  ...epkPressItems,{ outlet: "CBS Mornings", title: "Tyler Carson, the Fiddler on the Rock", href: "/cbs", sourceHref: "https://www.paramountplus.com/shows/video/HEu80JjRaVEH_kIOyf9dZ_OAj0cOctMD/", summary: "National feature on Tyler's Sedona story, voice loss, resilience, and performance with Lindsey Stirling.", featured: true }, { outlet: "Voyage Phoenix", title: "Daily Inspiration: Meet Tyler Carson", href: "https://voyagephoenix.com/interview/daily-inspiration-meet-tyler-carson/", summary: "Interview profile covering Tyler's path, creative life, and work as Fiddler on the Rock." }, { outlet: "JournalAZ", title: "Fiddler on the Rock to play weekly at museum", href: "https://journalaz.com/2025/09/20/fiddler-on-the-rock-to-play-weekly-at-museum/", summary: "Local coverage of Tyler's weekly concert series at the Sedona Heritage Museum." }, { outlet: "RE/MAX Sedona", title: "Things to Do Thursday", href: "https://www.remax-sedona-az.com/blog/things-to-do-thursday-74.html/print", summary: "Local things-to-do mention positioning Fiddler on the Rock as a Sedona evening option." }];
export const testimonials = [{ quote: "We flew in from Austin and this was, without question, the highlight of our entire trip. We've been to Sedona three times. Nothing comes close to this.", author: "Karen M.", context: "Google five-star review, Austin, TX" }, { quote: cbs.quote, author: "Lindsey Stirling", context: "CBS Mornings" }, { quote: "EXTRAORDINARY doesn't even begin to describe this multi-talented performer, composer, and musical genius.", author: "Patrick Schweiss", context: "Sedona International Film Festival" }];
export const reviews = [{ platform: "Google", rating: "5.0", count: "120+ Five-Star Reviews", quote: testimonials[0].quote, author: "Karen M.", source: "Google review" }, { platform: "Tripadvisor", rating: "5.0", count: "80+ Reviews", quote: "A Sedona experience unlike anything else.", author: "Guest review", source: "Tripadvisor" }, { platform: "Yelp", rating: "5.0", count: "30+ Reviews", quote: "Music, views, and the feeling that you found something rare.", author: "Guest review", source: "Yelp" }, { platform: "Facebook", rating: "Recommended", count: "99% Recommended", quote: "An unforgettable night in the Red Rocks.", author: "Guest recommendation", source: "Facebook" }];
export const ratingApiPlan = [];
export const videos = [{ title: "CBS Mornings Feature", href: "/cbs", type: "National feature", youtubeId: cbs.youtubeId }, { title: "Living Music Documentary", href: "/documentary", type: "Documentary", youtubeId: documentary.youtubeId }, { title: "Red Rock Performance", href: "/videos", type: "Performance archive", youtubeId: cbs.youtubeId }];
export const musicItems = [{ title: "Living Music", detail: "Original music shaped by presence, recovery, and the Red Rock landscape." }, { title: "One Man Symphony", detail: "Looped violin arrangements that turn one performer into an orchestra." }, { title: "Legends of the Fiddle", detail: "Mythic concert pieces, Celtic fire, classical lift, and cinematic storytelling." }];
export const merchItems = [{ title: "Logo Apparel", detail: "Shirts, hoodies, and wearable pieces featuring the Fiddler on the Rock emblem." }, { title: "Music & Keepsakes", detail: "Physical albums, signed posters, and unique Sedona mementos to remember your experience." }, { title: "Gift Cards", detail: "Share the magic of a live performance with friends and family." }];
export const bookingChecklist = [];
export const support = { headline: "Help Fiddler on the Rock reach for the stars.", body: "The crowdfunding campaign supports the next chapter of Tyler's Living Music work. It is separate from ticketing and merch, and it gives supporters a way to help the project grow beyond a single Sedona evening.", href: site.indiegogo };

export const seoKeywords = ["things to do in Sedona", "live music Sedona", "Sedona concerts", "Sedona sunset concert", "Sedona entertainment", "private concert Sedona", "romantic things to do Sedona", "Sedona proposal ideas", "Sedona Serenades", "Tyler Carson CBS", "Sedona violin", "violin looping artist"];


export const hero = { ...home, ctaPrimary: home.primaryCta, ctaSecondary: home.secondaryCta };
export const cbsSection = { eyebrow: cbs.headline, headline: cbs.headline, body: cbs.subheadline, quote: cbs.quote, quoteAttribution: cbs.attribution, ctaPrimary: { label: "Read Tyler's Full Story", href: "/about" }, ctaSecondary: { label: "Watch the Full CBS Segment", href: "/cbs" }, youtubeId: cbs.youtubeId };
export const emailSignup = { headline: "Stay Connected", body: "Get first access to Thursday concert dates, behind-the-scenes from the Red Rocks, and music you won't hear anywhere else.", buttonLabel: "Join the List" };
export const experienceCards = experiences.map((item) => ({ id: item.id, tag: item.eyebrow, title: item.title, description: item.summary, cta: "Explore", href: item.href, accent: item.id === "sedona-serenades" }));
export const indiegogo = { href: site.indiegogo, headline: support.headline, body: support.body };
