import type { AvailabilitySlot, PublicShowId, SerenadesPackageId, ShowId, SourceAttribution, TicketTier } from "./types";
export const sourceOptions: { value: SourceAttribution; label: string }[] = [{ value: "internet_search", label: "Internet Search" }, { value: "visit_sedona", label: "Visit Sedona" }, { value: "cbs_mornings", label: "On TV (CBS Mornings)" }, { value: "word_of_mouth", label: "Word of Mouth" }, { value: "concierge", label: "Concierge" }, { value: "google_ad", label: "Google Ad" }, { value: "other", label: "Other" }];
export const publicShows: Record<PublicShowId, { title: string; weekday: number; startHour: number; startMinute: number; durationMinutes: number; capacity: number; image: string; tiers: Record<TicketTier, { label: string; adult: number; kid: number; underEight: number }> }> = {
  "one-man-symphony": { title: "One Man Symphony", weekday: 4, startHour: 17, startMinute: 45, durationMinutes: 90, capacity: 48, image: "/images/red-rock-concert.jpg", tiers: { general: { label: "General Admission", adult: 5500, kid: 2200, underEight: 0 }, vip: { label: "VIP Admission", adult: 8500, kid: 2200, underEight: 0 } } },
  "legends-of-the-fiddle": { title: "Legends of the Fiddle", weekday: 6, startHour: 18, startMinute: 45, durationMinutes: 90, capacity: 60, image: "/images/tyler-leaping.jpg", tiers: { general: { label: "General Admission", adult: 5500, kid: 2200, underEight: 0 }, vip: { label: "VIP Admission", adult: 8500, kid: 2200, underEight: 0 } } },
};
export const serenadesPackages: Record<SerenadesPackageId, { title: string; priceMode: "fixed" | "per_person" | "request"; amount: number; minGuests: number; maxGuests: number; requestOnly?: boolean; description: string }> = {
  romantic_escape: { title: "Romantic Escape", priceMode: "fixed", amount: 39900, minGuests: 2, maxGuests: 2, description: "Just the two of you, the red canyon, and music that makes time stop." },
  gathering: { title: "The Gathering", priceMode: "per_person", amount: 14900, minGuests: 3, maxGuests: 6, description: "Friends, family, a few couples together - the canyon sounds different when you share it." },
  celebration: { title: "The Celebration", priceMode: "per_person", amount: 12500, minGuests: 7, maxGuests: 10, description: "A bigger gathering, still intimate. Seven to ten people under the red cliffs." },
  memory_package: { title: "Sedona Memory Package", priceMode: "request", amount: 200000, minGuests: 2, maxGuests: 2, requestOnly: true, description: "Starts at $2,000 with photographer and 20+ edited photos. Five-day minimum; two to four weeks ahead recommended." },
  private_event: { title: "Private Event", priceMode: "request", amount: 5000, minGuests: 11, maxGuests: 99, requestOnly: true, description: "Custom location or 11+ guests. $50 coordination call path before quote." },
};
export const serenadesAddOns = { customSong: { label: "Custom song on violin", amount: 25000 }, chocolate: { label: "Handmade Organic Chocolate", amount: 5000 }, water: { label: "Artesian Spring Water", amount: 0 } };
function nextDatesForWeekday(weekday: number, count = 10) { const dates: Date[] = []; const now = new Date(); const d = new Date(now); d.setHours(12,0,0,0); while (dates.length < count) { if (d.getDay() === weekday && d > now) dates.push(new Date(d)); d.setDate(d.getDate()+1); } return dates; }
function isoFor(date: Date, hour: number, minute: number) { const d = new Date(date); d.setHours(hour, minute, 0, 0); return d.toISOString(); }
export function demoAvailability(showId: ShowId): AvailabilitySlot[] { if (showId === "sedona-serenades") { const slots: AvailabilitySlot[] = []; for (let i=3; i<33; i+=3) { const d = new Date(); d.setDate(d.getDate()+i); d.setHours(16,30,0,0); const end = new Date(d); end.setMinutes(end.getMinutes()+120); slots.push({ id: "serenade-"+i+"-secret", showId, startsAt: d.toISOString(), endsAt: end.toISOString(), capacity: 10, paidCount: 0, heldCount: 0, location: "secret_spot", label: "The Secret Spot" }); const d2 = new Date(d); d2.setHours(10,0,0,0); const e2 = new Date(d2); e2.setMinutes(e2.getMinutes()+120); slots.push({ id: "serenade-"+i+"-open", showId, startsAt: d2.toISOString(), endsAt: e2.toISOString(), capacity: 10, paidCount: 0, heldCount: 0, location: "open_air_spot", label: "The Open-Air Spot" }); } return slots; } const show = publicShows[showId as PublicShowId]; return nextDatesForWeekday(show.weekday).map((date, index) => { const starts = isoFor(date, show.startHour, show.startMinute); const end = new Date(starts); end.setMinutes(end.getMinutes()+show.durationMinutes); return { id: showId+"-"+index, showId, startsAt: starts, endsAt: end.toISOString(), capacity: show.capacity, paidCount: index === 2 ? show.capacity - 2 : 0, heldCount: 0, label: show.title }; }); }
export function remainingSeats(slot: AvailabilitySlot) { return Math.max(0, slot.capacity - slot.paidCount - slot.heldCount); }
export function isSoldOut(slot: AvailabilitySlot) { return Boolean(slot.soldOutOverride) || remainingSeats(slot) <= 0; }
